### ISSUE TITLE
 No such file or directory

### ISSUE THREAD

**Issue by senf666** [arxhr007/Aliens_eye#5]
The latest commit broke the following:

```
Traceback (most recent call last):
  File "aliens_eye.py", line 31, in <module>
    with open("/usr/bin/sites.json") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/sites.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aliens_eye.py", line 34, in <module>
    with open("/data/data/com.termux/files/usr/bin/sites.json") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/data/com.termux/files/usr/bin/sites.json')
```

**Comment by arxhr007** [comment]
solved ! ,
thanks for noticing😊
